language: node_js

node_js:

  - "12.18.3"

services:
  - postgresql

before_script:

  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install

script:

  - "npm test"

after_script:

  - "npm run coverage"

notifications:

  email: false

sudo: false
