version: "3"
services:
  phantom-backend:
    build: .
    depends_on:
      - postgres
    environment:
      DEV_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/phantom-backend/
      - /phantom-backend/node_modules
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
      
